### ISSUE TITLE
GPG key cannot be found

### ISSUE THREAD

**Issue by RuijieYu** [alerque/aur#12]
Not sure if this is the best place for it, but I cannot pull your GPG key. I looked at several top-searched sites including gnupg.net, sks-keyservers.net and ubuntu.com, none of which can find your key. The fact that I can still post this issue shows that I am connected to the internet and the only explanation to the problem is that your key is somehow pulled down from these keyservers.

**Comment by alerque** [comment]
Thanks for the report, I'll look into it.

**Comment by alerque** [comment]
I am unable to confirm this. My first check was to Ubuntu's key server:

```console
$ gpg --keyserver hkp://keyserver.ubuntu.com --search-key caleb@alerque.com
gpg: data source: http://162.213.33.8:11371
(1)     Caleb Maclennan <caleb@alerque.com>
          4096 bit RSA key 63CC496475267693, created: 2014-07-31
Keys 1-1 of 1 for "caleb@alerque.com".  Enter number(s), N)ext, or Q)uit > 1
gpg: key 63CC496475267693: "Caleb Maclennan <caleb@alerque.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

Looks like it is there to me. It also [shows up online](https://keyserver.ubuntu.com/pks/lookup?search=caleb%40alerque.com&fingerprint=on&op=index), where the current expiration date of 2022-02-16 is also visible, so it's current.

It also is showing up online from [keys.gnupg.net](http://keys.gnupg.net/pks/lookup?search=caleb%40alerque.com&fingerprint=on&op=index). `pools.sks-keyservers.net` is just redirecting me to `keys.gnupg.net`. I also checked the venerable [pgp.mit.edu](https://pgp.mit.edu/) and my key [seems to be there](https://pgp.mit.edu/pks/lookup?op=vindex&search=0x63CC496475267693) too.

Is it possible that you are trying to fetch keys via HKP/HKPS protocols but those ports are being blocked? You may try using HTTPS instead to see if you can load keys that way. Are you able to find and retrieve *other* people's keys?

**Comment by RuijieYu** [comment]
OK after a bit of further investigation, I found that the issue is twofold. One is that for some reason `gpg --recv-keys 63CC496475267693` is unsuccessful until I specify a keyserver to use; other is that the key URL from `https://wiki.archlinux.org/index.php/unofficial_user_repositories` does not return anything, which strengthened my belief that the key had become unavailable. After I have specified the keyserver, I was able to pull your public keys from the keyserver. Now I just need to figure out what happens when I leave the keyserver unspecified, but on your end things should be all set. 
Thanks.

**Comment by RuijieYu** [comment]
Here are some peculiarities for different keyservers' website that I have found:
for https://keyservers.ubuntu.com and https://key.gnupg.net, using `0xKEYID` (note the `0x`) seems to be mandatory; if `0x` is missing, it returns "not found";
for https://pgp.mit.edu, using `0xFINGERPRINT` (note the `0x`) seems to be mandatory; if `0x` is missing, it returns "not found". 
I was about to investigate `0xKEYID` for your public key, but apparently pgp.mit.edu returns 502/503 for me, so I cannot proceed further.

**Comment by alerque** [comment]
Thanks for the follow up. The pgp.mit.edu server does seem to be having problems. Even the link that I posted my comment above does not work for me now, 2 hours later. I'm getting (randomly) either 5-10 second page loads, a timeout error, or a proxy error. If their server issues continue beyond a day or so maybe I'll change the Wiki page to point to a different key server.

If there is anything else I can do to make it more accessible let me know, but it seems to be posted okay the issue is key-servers and their various idiosyncrasies. Given the way key propagation works I think it should be available anywhere you can successfully pull any other key, but the protocol and format nuances are unique to each key platform.
