### ISSUE TITLE
xiphos missing libsword-1.9.0.3837.so?

### ISSUE THREAD

**Issue by egeiro** [alerque/aur#15]
Hi, have just installed Arch Linux, added your repo and installed xiphos through pacman. I receive an error when attempting to run xiphos. The error is 

`xiphos: error while loading shared libraries: libsword-1.9.0.3837.so: cannot open shared object file: No such file or directory`

Could you advise or offer any suggestions please on where I could obtain this file?
Thanks, Gary

**Comment by alerque** [comment]
I might need to rebuild it if the SWORD library has updated. Thanks for reporting this, I'll see what happened.

**Comment by alerque** [comment]
My Xiphos build was built using the `sword-svn` package that's also in my repository because at the time the Arch Linux [community] copy of sword was out of date. I see that has changed, I'll rebuild to use that.

**Comment by alerque** [comment]
I'm having trouble rebuilding the packages at all, and we might have to fix this upstream. I'll report back here as soon as I have something for you! Thanks again for reporting this and sorry it's not usable at the moment.

**Comment by egeiro** [comment]
Thanks. I appreciate your time.

**Comment by alerque** [comment]
@egeiro This might take a little bit to fix, Arch Linux isn't the only distro for which builds have gone sideways but so far we don't have any solid clues as to why.

**Comment by alerque** [comment]
Thanks in large part to the efforts of @ildar in tracking down a work around, this package on Arch should be fixed again. For the time being I've added a patch to the AUR build, but the upstream issue is still open because we'll need to get a proper fix into the next release of Xiphos.

**Comment by egeiro** [comment]
All working here. Thanks to all involved in the fix.
