### ISSUE TITLE
python-booleanoperations broken

### ISSUE THREAD

**Issue by freder** [alerque/aur#21]
```
Preparing...
Cloning python-booleanoperations build files...
Checking python-booleanoperations dependencies...
Checking python-fontpens dependencies...
Cloning python-fontparts build files...
Checking python-fontparts dependencies...
Synchronizing package databases...
Warning: manjaro-hello: local (0.6.7-2) is newer than extra (0.6.6-6)
Resolving dependencies...
Checking inter-conflicts...
Warning: dependency cycle detected:
Warning: python-fontparts will be installed before its python-booleanoperations dependency
Warning: dependency cycle detected:
Warning: python-fontparts will be installed before its python-fontpens dependency

Building python-fontparts...
==> Making package: python-fontparts 0.9.10-2 (Fri 06 Aug 2021 01:01:01 PM CEST)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> python-fontpens
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
```

**Comment by alerque** [comment]
Thanks for the report.

It looks like you have old versions of dependencies installed; those older versions are the ones with incorrect dependencies listed.

You should be able to update if you do it in this order:

1. python-fonttools
1. python-fontpens
1. python-fontparts

Another way to do it would be to remove the old versions of all 3 of those packages plus this one, then start from scratch. I believe the dependencies are resolvable in their current form, it is only the old packages that have this circular issue.

If that doesn't work do let me know and I'll look into it further.

**Comment by freder** [comment]
thank you!

this fixed it:
- removed all packages in question + dependend package
- installed fontpens
- installed dependend package
