### ISSUE TITLE
ssl certificate problem

### ISSUE THREAD

**Issue by bshor** [alerque/aur#25]
Hello,

I'm seeing this when using paru in Garuda linux (arch derivative).

```
 alerque.db failed to download
error: failed retrieving file 'alerque.db' from arch.alerque.com : SSL certificate problem: certificate has expired
error: failed to synchronize all databases (download library error)

```

**Comment by trames57** [comment]
Same here using standard Arch... pacman -Syy

**Comment by alerque** [comment]
Thanks for the reports, this is fixed. My apologies for the down time. The backstory is that I've transferred almost all of my hosting to different servers and this subdomain's SSL certificate renewal didn't get transferred from the new host where the domain is to the old host where this still is. Also this caught me traveling internationally so I'm late noticing it myself. I've put an updated certificate in place and all should be well again.

**Comment by bshor** [comment]
Thanks! Strange that font manager is only available from you ...

**Comment by alerque** [comment]
There is a good chance I'll be moving font-manager to [community], it seems to get quite a lot of use and I don't think there are any packaging blockers. I'm traveling right now so it may not happen until December, but it is on my list to migrate.
