### ISSUE TITLE
Package `virtualbox-ext-oracle` is out of date since several months.

### ISSUE THREAD

**Issue by dreirund** [alerque/aur#26]
The package `virtualbox-ext-oracle` is out of date since several months:

In your repository:

`pacman -Si alerque/virtualbox-ext-oracle | grep '^Version'`:

    Version         : 6.1.18-1

In the AUR and in [other repositories](https://wiki.archlinux.org/title/unofficial_user_repositories):

`yay -Si aur/virtualbox-ext-oracle | grep -E '^Repository|^Version'`:

    Repository      : aur
    Version         : 6.1.26-1

`pacman -Si virtualbox-ext-oracle | grep -E '^Repository|^Version'`:

    Repository      : alerque
    Version         : 6.1.18-1
    Repository      : andontie-aur
    Version         : 6.1.26-1
    Repository      : chaotic-aur
    Version         : 6.1.26-1
    Repository      : seblu
    Version         : 6.1.26-1
    Repository      : sergej-repo
    Version         : 6.1.26-1

Can you make sure you update the packages in your repository regularly, or remove all packages you cannot follow up with from your repository?

Thanks for maintaining!

**Comment by alerque** [comment]
Thanks for the report. For some reason I did not have this package flagged for notifications in the AUR, which is usually how I keep my repo up to date for packages I am not the maintainer of. I've enabled notifications and will get this rebuilt.

**Comment by alerque** [comment]
Updated.
