### ISSUE TITLE
Package zettlr been out-of-date

### ISSUE THREAD

**Issue by Jatin794** [alerque/aur#27]
The package `zettlr` (and `zettlr-git` if you prefer) have been out-of-date since a while, so can you please update them? I kinda added the repo coz it's the only one which builds zettlr (https://pkgs.org/download/zettlr)

**Comment by alerque** [comment]
Yes I'll get this updated. I'm traveling internationally right now so repo builds are lagging a bit, but I'll get it posted eventually.

**Comment by alerque** [comment]
Done.

Note the package has two build options now, with an embedded binary pandoc or with a system dependency. My preference, and hence the build in my repo, is for the system dependency.
