### ISSUE TITLE
brave is out of date

### ISSUE THREAD

**Issue by ghost** [alerque/aur#28]
Currently using the brave-bin but I would like to use the hardware acceleration so can you update to the latest brave release please

It's been flagged out of date since the 1st of October in AUR

**Comment by alerque** [comment]
I am currently on the road and my laptop does not have enough horsepower to test build brave. Please also see #24. You can easily use that PR and/or bump the version yourself to run a build. I will also accept PRs that are confirmed to build and run with the default options in a clean chroot, but so far we don't have that confirmation from anybody.
