### ISSUE TITLE
Package fontship needs to be rebuild for libgit2 version 1.4.

### ISSUE THREAD

**Issue by cionx** [alerque/aur#35]
I installed `fontship` from the provided Pacman repository, but the program crashes.
```bash
$ fontship --help
fontship: error while loading shared libraries: libgit2.so.1.3: cannot open shared object file: No such file or directory
```
The current version of the package has been built on December 15 and seems to search for version `1.3` of `libgit2`, which was the current version at the time. But it has since then been replaced by version `1.4` in the official repositories (first `1.4.1` and then the current version `1.4.2`).
```bash
$ pacman -Ql libgit2 | grep libgit2.so
libgit2 /usr/lib/libgit2.so
libgit2 /usr/lib/libgit2.so.1.4
libgit2 /usr/lib/libgit2.so.1.4.0
```
Rebuilding the packages seems to fix the problem: I did so using the `PKGBUILD` provided on the AUR, and the problem disappears.

(I’m not sure if this is the right place to report this problem, given that the `PKGBUILD` itself seems to be okay. But this repository is the only place mentioned in the [ArchWiki][archwiki].)

[archwiki]: https://wiki.archlinux.org/title/Unofficial_user_repositories#alerque

**Comment by alerque** [comment]
Thanks for the heads up. A rebuild is running now and should be in the repo in o few minutes.

**Comment by alerque** [comment]
And done.
