### ISSUE TITLE
Synching fails with `SSL: no alternative certificate subject name matches target host name 'arch.alerque.com'`.

### ISSUE THREAD

**Issue by dreirund** [alerque/aur#36]
When syncing, I now get the error `SSL: no alternative certificate subject name matches target host name 'arch.alerque.com'`:

`pacman -Sy`:
```
 alerque.db failed to download
error: failed retrieving file 'alerque.db' from arch.alerque.com : SSL: no alternative certificate subject name matches target host name 'arch.alerque.com'
error: failed to synchronize all databases (download library error)
```

**Comment by alerque** [comment]
Thanks for the report. I'm having trouble with pacman too. The cert shows as up to date in the browser through so I'm confused what happened. I'll be looking into it.

**Comment by alerque** [comment]
It's DNS. I screwed up DNS and some requests are hitting an old legacy server, some hitting a new one. Working on it...

**Comment by alerque** [comment]
This should be resolved. If you have a DNS resolver cache it might need a poke, but it should clear up soon. Thanks again for the report and sorry for the disruption.
