### ISSUE TITLE
[rasdaemon] Out of date.

### ISSUE THREAD

**Issue by dreirund** [alerque/aur#61]
The package `alerque/rasdaemon` is out of date:

* alerque/rasdaemon: 0.7.0-1
* [aur/rasdaemon](https://aur.archlinux.org/packages/rasdaemon): 0.8.0-1
* [Upstream](https://github.com/mchehab/rasdaemon/tags): 0.8.0

Regards!

**Comment by alerque** [comment]
Built and published.
