### ISSUE TITLE
[ qsv ] error: could not compile `polars-core` (lib)

### ISSUE THREAD

**Issue by dulfox** [alerque/aur#70]
I'm using manjaro on a raspberrypi (gcc 12.1.0, rustc  1.74.1)
Usually everything goes well for AUR package that I have to compile by my own.
Here for this package (0.118.0) I couldn't compile **polars-core** (lib) and I can't figure out why ?

`error: could not compile `polars-core` (lib)

Caused by:
  process didn't exit successfully: `rustc --crate-name polars_core --edition=2021 /home/pi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-core-0.34.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=237 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C linker-plugin-lto -C codegen-units=1 --cfg 'feature="abs"' --cfg 'feature="algorithm_group_by"' --cfg 'feature="asof_join"' --cfg 'feature="chrono"' --cfg 'feature="chunked_ids"' --cfg 'feature="comfy-table"' --cfg 'feature="docs"' --cfg 'feature="dtype-date"' --cfg 'feature="dtype-datetime"' --cfg 'feature="dtype-duration"' --cfg 'feature="dtype-struct"' --cfg 'feature="dtype-time"' --cfg 'feature="dtype-u16"' --cfg 'feature="dtype-u8"' --cfg 'feature="fmt"' --cfg 'feature="lazy"' --cfg 'feature="object"' --cfg 'feature="parquet"' --cfg 'feature="performant"' --cfg 'feature="rand"' --cfg 'feature="rand_distr"' --cfg 'feature="random"' --cfg 'feature="regex"' --cfg 'feature="reinterpret"' --cfg 'feature="rows"' --cfg 'feature="serde_json"' --cfg 'feature="strings"' --cfg 'feature="temporal"' --cfg 'feature="zip_with"' -C metadata=89ba363600a47603 -C extra-filename=-89ba363600a47603 --out-dir /var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps -C strip=symbols -L dependency=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps --extern ahash=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps/libahash-6ce2095132eb6d86.rmeta --extern bitflags=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps/libbitflags-0d7a2659c945b66a.rmeta --extern bytemuck=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps/libbytemuck-a66bb690964d5fca.rmeta --extern chrono=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps/libchrono-3fe9676179f93359.rmeta --extern comfy_table=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps/libcomfy_table-ab740792a4efaae3.rmeta --extern either=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps/libeither-08a9195ecc2e0929.rmeta --extern hashbrown=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps/libhashbrown-66f39cdbd2fc30e6.rmeta --extern indexmap=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps/libindexmap-6ea433942d8fd7ea.rmeta --extern num_traits=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps/libnum_traits-e30465d28ce4416e.rmeta --extern once_cell=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps/libonce_cell-bd5c88a9dcd6890f.rmeta --extern arrow=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps/libpolars_arrow-2b886dc050832655.rmeta --extern polars_error=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps/libpolars_error-57ad7e27e09cd634.rmeta --extern polars_row=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps/libpolars_row-eab37fac2791af93.rmeta --extern polars_utils=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps/libpolars_utils-c9fb722827574b3c.rmeta --extern rand=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps/librand-2950863e59a7a822.rmeta --extern rand_distr=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps/librand_distr-6440118000219b84.rmeta --extern rayon=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps/librayon-c94f9dbb79e7b6c6.rmeta --extern regex=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps/libregex-671c669591144a10.rmeta --extern serde_json=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps/libserde_json-2edb35ef54da9dbf.rmeta --extern smartstring=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps/libsmartstring-91d38f77853ca7c9.rmeta --extern thiserror=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps/libthiserror-38192a1cc8503d67.rmeta --extern xxhash_rust=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/deps/libxxhash_rust-db8b04d5371c7553.rmeta --cap-lints allow -C 'link-args=-Wl,-rpath,$ORIGIN' -L native=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/build/lz4-sys-5ee78c18525ac4f1/out -L native=/var/tmp/pamac-build-pi/qsv/src/qsv-0.118.0/target/release/build/zstd-sys-2d28e52f8c40536b/out` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
`

- **Where are the logs ? (couldn't find any interesting reporting the root cause)**
- **If it is not doable within the PKGBUILD, how can I try to compile it alone to check for the errors ?**

I've tryied to update to the latest release (0.119.0) because I saw this [anwer ](https://github.com/jqnatividad/qsv/issues/1431#issuecomment-1819989988) but I get the same kind of error (it seems you didn't get any answer :-( )

**Comment by alerque** [comment]
Almost certainly some external library is not ARM compatible.

If you don't need polars support, just remove it from the features list in the PKGBUILD.

If you do, then I suggest just cloning and building the upstream project directly with `cargo` to get more direct access to debug logs and such, then reporting this upstream. It's probably not ever the QSV project but whatever project has the polars-core crate in it that needs to implement a fix.

If it does turn out there is some combination of flags and dependencies we can setup so the PKGBUILD works I'm happy to accept contributions, but I'm not able to test on ARM much less Manjaro.

**Comment by dulfox** [comment]
Thanks for your quick answer @alerque.
I will keep you posted as soon as I have any result.

**Comment by dulfox** [comment]
I switched to 0.119.0 sources without polars features and I was able to compile !
` Finished release [optimized] target(s) in 34m 36s`
You might try to see if it also works for you.
To be honest I don't know if I need polars or not but I would like to understand or at least see the error.
I've requested rust community's [help](https://users.rust-lang.org/t/error-could-not-compile-polars-core-lib/104626) as well.
I will let you know.

**Comment by alerque** [comment]
I'll bump to 0.119 anyway, but I doubt it will have any effect on your issue.

The polars feature enables the `joinp` command. The QSV readme has details.

Since it works on everything with official Arch support I'm going to leave the feature enabled. Do report back if you find out some way to build on ARM.

**Comment by alerque** [comment]
I've been updating this package and the last couple versions have compiled fine with the polars  feature on x84_64. I suggest opening an issue upstream about the issue building on ARM since it isn't something I can fix in packaging.
