### ISSUE TITLE
Source file fails checksum validation in lua51-lsqlite3 and lua-lsqlite3 packages

### ISSUE THREAD

**Issue by AvianAnalyst** [alerque/aur#79]
Hello! I'm a newbie, so I apologize if I'm missing something. But a couple  programs I use depend on lua51-lsqlite3 and lua-lqlite3 respectively. However when I try to update them, I get errors from your packages about the checksum failing validation. I've tried redownloading multiple times with yay -S --redownload <pkg> and yay -S <pkg> --redownload and yay --redownload -S <pkg>, additionally both packages in the AUR have a comment from another user with the same issue. 

Please let me know if I can do something to fix this, or what my next steps should be. Thank you!

**Comment by alerque** [comment]
It looks like upstream fiddled with something. I did *not* confirm if anything changed in the ZIP, but the upstream hosted file has changed somehow. I've updated the package to match, although it would really be smart to dig into the difference and see what changed under the hood.
