### ISSUE TITLE
github-desktop is out of date

### ISSUE THREAD

**Issue by Bryan2333** [alerque/aur#92]
`github-desktop` is out of data as upstream has released [3.4.8](https://github.com/shiftkey/desktop/releases/tag/release-3.4.8-linux1).

Besides, `python` should be added to makedepends, otherwise the package will fail to build in clean chroot environment.

**Comment by alerque** [comment]
Thanks. I'd already tried to bump this but saw it did not build cleanly in a chroot (which I do for *all* my packages) so it didn't get posted yet—and I didn't get a chance to circle back and figure out what the hang up was. I have a test build running now with python, if that works I'll post the bump soon.

Feel free to send PRs too. Maybe not for pure version bumps as I can do those automatically anyway, but any time the builds need actual adjustment I'm open to merging a contribution.

**Comment by alerque** [comment]
Unfortunately just adding python isn't enough to build 3.4.8 in a clean chroot. It's choking on some node build steps and I don't see an obvious thing to try next. ~~If you do and have a working build please do feel free to share.~~ Looks like it was `python-setuptools` it needed.
